/*
 * Levels on the site. Each level's topic files live in content/<id>/ and are listed in `files`
 * (without ".js"). Topic ids are "1.3" style (group = part before the dot) or "N3" style
 * (group = the letters). `groups` sets the order and headings; `sections` group the groups.
 */
H2.setLevels([
  {
    id: "h2",
    name: "H2 Mathematics",
    short: "H2 Math",
    stage: "A-Level · JC",
    code: "9758",
    eyebrow: "Singapore-Cambridge GCE A-Level · Syllabus 9758",
    summary: "Functions, sequences, vectors, complex numbers, calculus, and probability and statistics.",
    storeKey: "h2math:confident:v1",
    noCalcLabel: "No GC",
    papers: [
      { title: "Paper 1 · 3 h · 100 marks", text: "10–12 questions on Pure Mathematics, including one application question in a real-world context (at least 12 marks)." },
      { title: "Paper 2 · 3 h · 100 marks", text: "Section A: Pure Mathematics (40 marks, 4–5 questions). Section B: Probability and Statistics (60 marks, 6–8 questions), including one application question." },
    ],
    sections: [
      { id: "A", title: "Section A · Pure Mathematics" },
      { id: "B", title: "Section B · Probability and Statistics" },
      { id: "IP", title: "Beyond the syllabus · IP extensions" },
    ],
    groups: [
      { id: "1", title: "Functions and Graphs", section: "A" },
      { id: "2", title: "Sequences and Series", section: "A" },
      { id: "3", title: "Vectors", section: "A" },
      { id: "4", title: "Introduction to Complex Numbers", section: "A" },
      { id: "5", title: "Calculus", section: "A" },
      { id: "6", title: "Probability and Statistics", section: "B" },
      { id: "X", title: "IP Extensions", section: "IP" },
    ],
    tagInfo: { IP: "Beyond the 9758 syllabus (including topics removed from it for exams from 2025). Often taught in IP schools or for H2 Further Mathematics and H3; not examined in H2 Mathematics." },
    footnote: String.raw`Follows the SEAB 9758 syllabus (2026 and 2027 exams). All questions are original. Formulae marked <span class="mf">MF27</span> are in the List of Formulae.`,
    files: [
      "1.1-functions", "1.2-graphs-transformations", "1.3-equations-inequalities",
      "2.1-sequences-series",
      "3.1-vectors-basic", "3.2-scalar-vector-products", "3.3-lines-planes",
      "4.1-complex-numbers",
      "5.1-differentiation", "5.2-maclaurin-series", "5.3-integration-techniques", "5.4-definite-integrals", "5.5-differential-equations",
      "6.1-probability", "6.2-discrete-random-variables", "6.3-normal-distribution", "6.4-sampling", "6.5-hypothesis-testing", "6.6-correlation-regression",
      "X1-complex-polar-exponential", "X2-proof-by-induction",
    ],
  },
  {
    id: "emath",
    name: "Mathematics (E-Math)",
    short: "E-Math",
    stage: "Secondary · O-Level / SEC",
    code: "K310",
    eyebrow: "SEC G3 Mathematics · Syllabus K310 (O-Level 4052)",
    summary: "Number and algebra, geometry and measurement, and statistics and probability.",
    noCalcLabel: "No calculator",
    papers: [
      { title: "Paper 1 · 2 h 15 min · 90 marks", text: "About 26 short-answer questions. Calculator allowed." },
      { title: "Paper 2 · 2 h 15 min · 90 marks", text: "9–10 longer questions. The last question applies mathematics to a real-world scenario. Calculator allowed." },
    ],
    sections: [{ id: "all", title: "" }],
    groups: [
      { id: "N", title: "Number and Algebra", section: "all" },
      { id: "G", title: "Geometry and Measurement", section: "all" },
      { id: "S", title: "Statistics and Probability", section: "all" },
    ],
    tagInfo: { IP: "Beyond the K310 syllabus. Often taught in IP schools; not examined in E-Math." },
    footnote: String.raw`Follows the SEAB SEC G3 Mathematics syllabus K310 (first exam 2027), which has the same content as O-Level 4052. All questions are original. Formulae marked <span class="mf">Given</span> are on the formula sheet in the exam paper.`,
    files: [
      "N1-numbers-operations", "N2-ratio-proportion", "N3-percentage", "N4-rate-speed", "N5-algebraic-expressions",
      "N6-functions-graphs", "N7-equations-inequalities", "N8-sets", "N9-matrices",
      "G1-angles-triangles-polygons", "G2-congruence-similarity", "G3-circle-properties", "G4-pythagoras-trigonometry",
      "G5-mensuration", "G6-coordinate-geometry", "G7-vectors",
      "S1-data-analysis", "S2-probability",
    ],
  },
  {
    id: "amath",
    name: "Additional Mathematics (A-Math)",
    short: "A-Math",
    stage: "Secondary · O-Level / SEC",
    code: "K341",
    eyebrow: "SEC G3 Additional Mathematics · Syllabus K341 (O-Level 4049)",
    summary: "Algebra, geometry and trigonometry, and calculus. Assumes E-Math.",
    noCalcLabel: "No calculator",
    papers: [
      { title: "Paper 1 · 2 h 15 min · 90 marks", text: "12–14 questions, up to 10 marks each. Calculator allowed." },
      { title: "Paper 2 · 2 h 15 min · 90 marks", text: "9–11 questions, up to 12 marks each. Calculator allowed." },
    ],
    sections: [{ id: "all", title: "" }, { id: "IP", title: "Beyond the syllabus · IP extensions" }],
    groups: [
      { id: "A", title: "Algebra", section: "all" },
      { id: "G", title: "Geometry and Trigonometry", section: "all" },
      { id: "C", title: "Calculus", section: "all" },
      { id: "X", title: "IP Extensions", section: "IP" },
    ],
    tagInfo: { IP: "Beyond the K341 syllabus (including topics removed from older O-Level A-Math). Often taught in IP schools; not examined in A-Math." },
    footnote: String.raw`Follows the SEAB SEC G3 Additional Mathematics syllabus K341 (first exam 2027), which has the same content as O-Level 4049. All questions are original. Formulae marked <span class="mf">Given</span> are on the formula sheet in the exam paper.`,
    files: [
      "A1-quadratic-functions", "A2-equations-inequalities", "A3-surds", "A4-polynomials-partial-fractions",
      "A5-binomial-expansions", "A6-exponential-logarithmic",
      "G1-trigonometry", "G2-coordinate-geometry", "G3-plane-geometry-proofs",
      "C1-differentiation", "C2-applications-of-differentiation", "C3-integration", "C4-kinematics",
      "X1-modulus-functions", "X2-functions", "X3-graph-transformations",
    ],
  },
  {
    id: "olympiad-primary",
    kind: "olympiad",
    name: "Primary Math Olympiad",
    short: "Olympiad (Primary)",
    stage: "Primary · P4–P6",
    code: "Olympiad",
    eyebrow: "Problem solving beyond the PSLE syllabus",
    summary: "Non-routine problems by theme, in the style of SASMO, NMOS, SMOPS and RIPMWC.",
    lede: "Key ideas and common problem types for each theme, with problems graded by difficulty. Answers can be revealed; methods are taught in class.",
    noCalcLabel: "No calculator",
    sections: [{ id: "all", title: "" }],
    groups: [
      { id: "N", title: "Numbers", section: "all" },
      { id: "C", title: "Counting and Logic", section: "all" },
      { id: "W", title: "Word Problem Methods", section: "all" },
      { id: "G", title: "Geometry", section: "all" },
    ],
    footnote: "All problems are original, written in the style of Singapore primary mathematics competitions.",
    files: [
      "N1-whole-numbers-digits", "N2-factors-multiples", "N3-patterns-sequences", "N4-fractions-ratio",
      "C1-counting", "C2-logic-puzzles", "C3-parity-pigeonhole-games",
      "W1-supposition-excess-shortage", "W2-working-backwards-model", "W3-speed-distance-work",
      "G1-angles-figures", "G2-area-perimeter", "G3-solids-nets",
    ],
  },
]);
